### ISSUE TITLE
Database Scheme

### ISSUE THREAD

**Issue by sonmezonur** [gokcan/Spring-Secured-PDF#1]
First of all, thanks for well-prepared repository. There is a lot to learn in this post.  Additionally, i think it would be nice to have sql scheme, thus users can pass sql scheme directly to database.

**Comment by gokcan** [comment]
Hi there! 
I have fully turned all of the DDL statements to _Hibernate column annotations_  and changed the configs so that you do not need to write any DDL statements or use scheme creation files (e.g. data.sql) before running the project. 

Just change **spring.datasource.password** with your own mysql root password.
[application.properties](https://github.com/Skylifee7/Spring-Secured-PDF/blob/master/src/main/resources/application.properties)

Please see ce412a5
Thanks for your feedback.

**Comment by sonmezonur** [comment]
Good enough! Thanks for the update.
